<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocumentSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();
        $adminId = DB::table('users')->where('role', 'admin')->value('id');
        $bandDirId = DB::table('users')->where('email', 'director.band@unc.edu.ph')->value('id');
        $choirDirId = DB::table('users')->where('email', 'director.glee@unc.edu.ph')->value('id');
        $danceDirId = DB::table('users')->where('email', 'director.dance@unc.edu.ph')->value('id');
        $theaterDirId = DB::table('users')->where('email', 'director.majorettes@unc.edu.ph')->value('id');

        $documents = [
            // ── Scholarship Contracts ──────────────────────────────────────────────
            [
                'title'       => 'Scholarship Contract – Juan Dela Cruz (Marching Band)',
                'file_path'   => 'documents/contracts/scholarship_juan_delacruz_2025.pdf',
                'file_name'   => 'scholarship_juan_delacruz_2025.pdf',
                'file_size'   => '245 KB',
                'file_type'   => 'application/pdf',
                'user_id'     => $adminId,
                'category'    => 'scholarship-contract',
                'talent_group'=> 'marching-band',
                'related_to'  => 'Juan Dela Cruz',
                'uploaded_by' => 'Admin User',
                'description' => 'Official scholarship contract for AY 2025–2026, first semester. Covers full tuition and monthly stipend.',
                'tags'        => json_encode(['contract', 'marching-band', '2025', 'first-sem']),
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'title'       => 'Scholarship Contract – Maria Santos (Glee Club)',
                'file_path'   => 'documents/contracts/scholarship_maria_santos_2025.pdf',
                'file_name'   => 'scholarship_maria_santos_2025.pdf',
                'file_size'   => '238 KB',
                'file_type'   => 'application/pdf',
                'user_id'     => $adminId,
                'category'    => 'scholarship-contract',
                'talent_group'=> 'glee-club',
                'related_to'  => 'Maria Santos',
                'uploaded_by' => 'Admin User',
                'description' => 'Scholarship contract for AY 2025–2026. Covers 75% tuition discount and performance allowance.',
                'tags'        => json_encode(['contract', 'glee-club', '2025']),
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'title'       => 'Scholarship Contract – Ana Reyes (Dance Club)',
                'file_path'   => 'documents/contracts/scholarship_ana_reyes_2025.pdf',
                'file_name'   => 'scholarship_ana_reyes_2025.pdf',
                'file_size'   => '251 KB',
                'file_type'   => 'application/pdf',
                'user_id'     => $adminId,
                'category'    => 'scholarship-contract',
                'talent_group'=> 'dance-club',
                'related_to'  => 'Ana Reyes',
                'uploaded_by' => 'Admin User',
                'description' => 'Dance Club scholarship agreement for second semester AY 2025–2026.',
                'tags'        => json_encode(['contract', 'dance-club', '2025', 'second-sem']),
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'title'       => 'Scholarship Renewal Contract – Carlo Mendoza (Marching Band)',
                'file_path'   => 'documents/contracts/renewal_carlo_mendoza_2026.pdf',
                'file_name'   => 'renewal_carlo_mendoza_2026.pdf',
                'file_size'   => '260 KB',
                'file_type'   => 'application/pdf',
                'user_id'     => $adminId,
                'category'    => 'scholarship-contract',
                'talent_group'=> 'marching-band',
                'related_to'  => 'Carlo Mendoza',
                'uploaded_by' => 'Admin User',
                'description' => 'Renewal contract for AY 2026–2027 pending GPA verification.',
                'tags'        => json_encode(['renewal', 'marching-band', '2026', 'pending']),
                'status'      => 'pending',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            // ── Event Requests ────────────────────────────────────────────────────
            [
                'title'       => 'Event Request – UNC Foundation Day Performance',
                'file_path'   => 'documents/requests/event_request_foundation_day_2026.pdf',
                'file_name'   => 'event_request_foundation_day_2026.pdf',
                'file_size'   => '182 KB',
                'file_type'   => 'application/pdf',
                'user_id'     => $bandDirId,
                'category'    => 'event-request',
                'talent_group'=> 'marching-band',
                'related_to'  => 'UNC Foundation Day',
                'uploaded_by' => 'Band Director',
                'description' => 'Formal request for Marching Band and Majorettes to perform at the UNC Foundation Day celebration on June 15, 2026.',
                'tags'        => json_encode(['event-request', 'foundation-day', '2026', 'marching-band', 'majorettes']),
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'title'       => 'Event Request – Peñafrancia Festival Participation',
                'file_path'   => 'documents/requests/event_request_penafrancia_2026.pdf',
                'file_name'   => 'event_request_penafrancia_2026.pdf',
                'file_size'   => '195 KB',
                'file_type'   => 'application/pdf',
                'user_id'     => $bandDirId,
                'category'    => 'event-request',
                'talent_group'=> 'marching-band',
                'related_to'  => 'Peñafrancia Festival',
                'uploaded_by' => 'Band Director',
                'description' => 'Request to participate in the Peñafrancia Festival Street Parade on September 8, 2026. Requires 3 days of extra rehearsals.',
                'tags'        => json_encode(['event-request', 'penafrancia', 'festival', '2026']),
                'status'      => 'pending',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'title'       => 'Event Request – Bicol Regional Arts Competition',
                'file_path'   => 'documents/requests/event_request_regional_arts_2026.pdf',
                'file_name'   => 'event_request_regional_arts_2026.pdf',
                'file_size'   => '210 KB',
                'file_type'   => 'application/pdf',
                'user_id'     => $choirDirId,
                'category'    => 'event-request',
                'talent_group'=> 'glee-club',
                'related_to'  => 'Bicol Regional Arts Competition',
                'uploaded_by' => 'Choir Director',
                'description' => 'Competition entry request for Glee Club and Dance Club at the Bicol Regional Arts Competition on August 10, 2026.',
                'tags'        => json_encode(['competition', 'regional', 'glee-club', 'dance-club', '2026']),
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            // ── Event Approvals ───────────────────────────────────────────────────
            [
                'title'       => 'Approval – Independence Day Ceremony Participation',
                'file_path'   => 'documents/approvals/approval_independence_day_2026.pdf',
                'file_name'   => 'approval_independence_day_2026.pdf',
                'file_size'   => '156 KB',
                'file_type'   => 'application/pdf',
                'user_id'     => $adminId,
                'category'    => 'event-approval',
                'talent_group'=> 'marching-band',
                'related_to'  => 'Naga City Independence Day Celebration',
                'uploaded_by' => 'Admin User',
                'description' => 'Official approval letter from the City Government for UNC Marching Band participation in the June 12 Independence Day ceremony.',
                'tags'        => json_encode(['approval', 'government', 'independence-day', '2026']),
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'title'       => 'Approval – Graduation Ceremony Music Program',
                'file_path'   => 'documents/approvals/approval_graduation_2026.pdf',
                'file_name'   => 'approval_graduation_2026.pdf',
                'file_size'   => '143 KB',
                'file_type'   => 'application/pdf',
                'user_id'     => $adminId,
                'category'    => 'event-approval',
                'talent_group'=> 'marching-band',
                'related_to'  => 'UNC Graduation Ceremony',
                'uploaded_by' => 'Admin User',
                'description' => 'University approval for Marching Band processional and Glee Club vocal performance at the July 2026 graduation ceremony.',
                'tags'        => json_encode(['approval', 'graduation', '2026', 'marching-band', 'glee-club']),
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            // ── Performance Reports ───────────────────────────────────────────────
            [
                'title'       => 'Performance Report – Intramurals Opening Ceremony',
                'file_path'   => 'documents/reports/performance_report_intramurals_2026.pdf',
                'file_name'   => 'performance_report_intramurals_2026.pdf',
                'file_size'   => '312 KB',
                'file_type'   => 'application/pdf',
                'user_id'     => $bandDirId,
                'category'    => 'performance-report',
                'talent_group'=> 'marching-band',
                'related_to'  => 'UNC Intramurals Opening Ceremony',
                'uploaded_by' => 'Band Director',
                'description' => 'Post-event report for the March 25 Intramurals Opening Ceremony. Attendance: 32/35 members present. Performance rated excellent.',
                'tags'        => json_encode(['report', 'intramurals', '2026', 'completed']),
                'status'      => 'completed',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'title'       => 'Performance Report – Teacher Recognition Day',
                'file_path'   => 'documents/reports/performance_report_teacher_day_2026.pdf',
                'file_name'   => 'performance_report_teacher_day_2026.pdf',
                'file_size'   => '278 KB',
                'file_type'   => 'application/pdf',
                'user_id'     => $choirDirId,
                'category'    => 'performance-report',
                'talent_group'=> 'glee-club',
                'related_to'  => 'Teacher Recognition Day Program',
                'uploaded_by' => 'Choir Director',
                'description' => 'Glee Club performance report for the April 5 Teacher Recognition Day. Performed 4 pieces. All members present.',
                'tags'        => json_encode(['report', 'glee-club', 'teachers-day', '2026', 'completed']),
                'status'      => 'completed',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            // ── Scholar Records ───────────────────────────────────────────────────
            [
                'title'       => 'Scholar Records – Marching Band AY 2025–2026',
                'file_path'   => 'documents/records/scholars_marching_band_2025_2026.pdf',
                'file_name'   => 'scholars_marching_band_2025_2026.pdf',
                'file_size'   => '520 KB',
                'file_type'   => 'application/pdf',
                'user_id'     => $adminId,
                'category'    => 'scholar-records',
                'talent_group'=> 'marching-band',
                'related_to'  => 'All Marching Band Scholars',
                'uploaded_by' => 'Admin User',
                'description' => 'Complete roster and academic records of Marching Band scholars for AY 2025–2026. Includes GPA, attendance rate, and scholarship status.',
                'tags'        => json_encode(['records', 'roster', 'marching-band', '2025-2026']),
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'title'       => 'Scholar Records – Glee Club AY 2025–2026',
                'file_path'   => 'documents/records/scholars_glee_club_2025_2026.pdf',
                'file_name'   => 'scholars_glee_club_2025_2026.pdf',
                'file_size'   => '445 KB',
                'file_type'   => 'application/pdf',
                'user_id'     => $adminId,
                'category'    => 'scholar-records',
                'talent_group'=> 'glee-club',
                'related_to'  => 'All Glee Club Scholars',
                'uploaded_by' => 'Admin User',
                'description' => 'Roster and academic records for Glee Club scholars. Includes voice classification, evaluation scores, and scholarship percentage.',
                'tags'        => json_encode(['records', 'roster', 'glee-club', '2025-2026']),
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'title'       => 'Scholar Records – Dance Club AY 2025–2026',
                'file_path'   => 'documents/records/scholars_dance_club_2025_2026.pdf',
                'file_name'   => 'scholars_dance_club_2025_2026.pdf',
                'file_size'   => '398 KB',
                'file_type'   => 'application/pdf',
                'user_id'     => $adminId,
                'category'    => 'scholar-records',
                'talent_group'=> 'dance-club',
                'related_to'  => 'All Dance Club Scholars',
                'uploaded_by' => 'Admin User',
                'description' => 'Dance Club scholar roster with performance evaluations and scholarship renewal status.',
                'tags'        => json_encode(['records', 'roster', 'dance-club', '2025-2026']),
                'status'      => 'approved',
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
        ];

        DB::table('documents')->insert($documents);
    }
}
